// Genere automatiquement : apercus flous affiches pendant le chargement.
export const blurMap: Record<string, string> = {
  "/images/chantier/baie-vitree-apres.webp": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQAgCdASoOAA4AAwBSJYgCdAdwBIW/9jjAAPyO+GeFKLUmJqLaYI5ZeZdJr9mGwRnqz2QW+WBg+AN2wKBE4AeUQIq9paCBXozSigFTfMVZCcB9Ck35r5dVBaMv0YKuM5g33HSD8NEzpdjlcly99Ku3uXxr1EAA",
  "/images/chantier/baie-vitree-avant.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoOAA4AAwBSJYwCdAED/t1Hk3utAAD+QS/DLA+N+I8Xh+NB7KKQBzz0zcw/INew6SWPRxXQW/aysuQwZ98X+Ahow6btvLT+X2oR8JFL6R96Dj7cDoQpalglwHtrYgAA",
  "/images/chantier/boutique-chantier-apres.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoOAA4AAwBSJQBOgBkuE0AAAPwputH0zoFH9c1BCBPs0gdN2pLzerICUVviCLAikkGVoNQfjiTKEOaHi42Ds+DTuCAAAA==",
  "/images/chantier/boutique-chantier-avant.webp": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoOAA4AAwBSJYgCdAEDup+XKxAAAP39NKewY5Z7g1LBhWWsEegX7Sui3BbMY4i1n8AzbgjnXHOAHQV9YOQnO6JooBC/88AA",
  "/images/chantier/bureau-apres.webp": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoOAA4AAwBSJZwAAu11M52KI6qgAP3G6bzk6Npad3knvm5K+vWxLTXdejiaorayFZpbS0DxLC9JXBv03GKEY6HpMx+DiNUAAAA=",
  "/images/chantier/bureau-avant.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoOAA4AAwBSJZwCw7DRMbEa/AAA/tKGZ6a/IEeD8ZgQ/vMygQNcOHoKsaaRtG3RUhjMWmQLTaD4CidFdScnccCYf7VLwa8JS/l8La/yFjAAAA==",
  "/images/chantier/dallage-exterieur-apres.webp": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoOAA4AAwBSJQBOgBodNtA3DZAA/mzrK9DQ9ha/5C1WlGH6YK76C4tqJdwJPWtt6UH4hgqEMmt08HYrc35bIdjNcm7AwAAA",
  "/images/chantier/dallage-exterieur-avant.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoOAA4AAwBSJYwAAuR5vgAA/uWJ2S4utZb3GaLbUfLHklQZBEjHwPuT8KgAAA==",
  "/images/chantier/hall-copropriete-apres.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoOAA4AAwBSJZQC7AEeZbYXwAD8XvwEGV3+6PqDQobEOZkGiOWFcDIq12JtplE28Hz0qKs8AAA=",
  "/images/chantier/hall-copropriete-avant.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoOAA4AAwBSJQBOgB00SigAAPZnBMiR7/IfZl53sczkY4E9uWJeA5uWyLhSV11oK4W6oUERKQAAAA==",
  "/images/chantier/hall-sol-apres.webp": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoOAA4AAwBSJZgCdADPoYEAAP6t5U+jKgQLN91XStn57FLVolDrai4Cesq0KEzy08DQNFd0MNMjQuX80gbnYzvN/YDROv7kAAA=",
  "/images/chantier/hall-sol-avant.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAQCdASoOAA4AAwBSJaACdABdSAD+0q1EFtq8J338peLvExhD7+77zjI+o2vS0BTR50XG4Zus8f0JwIP37GWQG+TyIp7cAAA=",
  "/images/chantier/local-commercial-apres.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoOAA4AAwBSJQBOgCEtPxQAAP40fVzjsIXOhM+8ct/nwWVsSv3e3TRf1HEH8wJ5lw/zUhe3uHPU8arCAAA=",
  "/images/chantier/local-commercial-avant.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoOAA4AAwBSJQBOgBb2afAlvG4AAPul5aaNS2buhSbhoZSS6zSYnbVR3V1WsBfIr51r6GPBxFggwdJ5j6xruRkZeSRXjidVgHcIoyUe3fzKQAAA",
  "/images/chantier/sanitaires-apres.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoOAA4AAwBSJZQCdAD6JbfLxIMbeAD+Tw3DiUJtJTWmqM2NOATy7cymTCs+7licjWGuC3i4Eg8s+kO5Xp6NXL0zEzM4X0bkaf3xew8z2ZMAAA==",
  "/images/chantier/sanitaires-avant.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoOAA4AAwBSJYwCdAEWywPe/sAAAM3Voh/8ZR7oeb6eM0D/exyMg/0BDBS0zxSVKvFF1h8/dGIw0Z2TsMAAAA==",
  "/images/chantier/terrasse-bois-apres.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoOAA4AAwBSJYgCdAD6JYQuSAAA/mSJMAU/r0fZf1CPKLxkjtd/Aqevz1caMPoYZxQD5QL8blWTntwAAAA=",
  "/images/chantier/terrasse-bois-avant.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoOAA4AAwBSJZQAAv3GMmw9xgAA/l5c8G/HArc1XqUnMPH3MloyQDUahkr8AyOa2ZN3/S4AAAA=",
  "/images/chantier/vitres-bureau-apres.webp": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoOAA4AAwBSJQBOgCB0lB4VHwAA+RBKLoePVxHdkZJXoOQ7Ze8hurQ4o2rs3XAFlr9IpfD5A14aaMdMBTd/+Icpa2mQxn6M/OUGCyO4A1gnS9PBVHiDlyoSAAA=",
  "/images/chantier/vitres-bureau-avant.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoOAA4AAwBSJZQC7AD1Dl3t/nAA+GJ5+90umsB3hxbcxjaEH6+UQs2592d34b654lLCX0KQiT0b9XEYHICLdej+6v977xxhjc9tqM7tAAA=",
  "/images/chantier/vitrine-boutique-apres.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoOAA4AAwBSJYgCdAEUVwf9ZqXGgAD+zd44Bp1EwwqSMxpffw6HBhX4dJlfNc4tlf5riRSnUTBjAOz8aanxm5fTqvkxvs59HPk6LeXRE02MAAAA",
  "/images/chantier/vitrine-boutique-avant.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoOAA4AAwBSJZQCdAEegIcQAAD+huqT/FMraz1fb7e6cCHcOpmu7RE72RlPJ0CoodtH+patcFVg1MIFzlQNpN3FvHt6ypjdfQspWLrAAAA=",
  "/images/chantier/vitrine-commerce-apres.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoOAA4AAwBSJYgCdADcGr7ELwAA9kHTR+cnSQ1Bdg+OVNU4unNFI3sz9tgHIjvLjTsVXFBvVN6rUd7K5PUWq2BloigQIIquJSg08+BogAA=",
  "/images/chantier/vitrine-commerce-avant.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoOAA4AAwBSJZQC7ACnlbsgAAD+mFrmn0t9wZB4dJU7SxtzilURqkww+4CDLnzdcHyCS3YrxI/0E7VWA7jvUNZGCBdemGQcRz/4qAAA",
  "/images/equipe/agent-bureaux.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoOAAgAAwBSJZQAD4rxeasGT/NdoAD+yYYw4pmgaQQu8lRGi4V/xQZ1cHPYhfmXfu8FXC0RuZK2Q3EGCbwZbvbEs23FuPSEw4ezVpKAlG5vH0aPA4AAAA==",
  "/images/equipe/agent-sol-couloir.webp": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoOAAgAAwBSJQBOj+ACyNlvQzOAAP5Pd3z6N2Tav3KZoz/e7rhoqk6JIPNndK2OSxBhI9V3IJpU2gyvE/asGZLPtK1hq69eNAA=",
  "/images/equipe/agent-vitres.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoOAAgAAwBSJZwAAqzGR2q/gADh6jPeaHN93SlMIyJnTMPRX+8umk/yI/4rbKKxCZyJpq8hkgGE9DkAAAA="
};
